# Generated by Django 4.2.7 on 2025-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]

